name: wechat_assets_picker
description: An audio/video/image picker in pure Dart which is the same with WeChat, support multi picking.
version: 6.3.1
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^6.0.1
  photo_manager: ^1.3.10
  provider: ^6.0.1
  video_player:
    git:
      url: https://github.com/xiaodunan/plugins.git
      ref: 35dc6ac
      path: packages/video_player/video_player/
